# Generated by Django 5.2.17 on 2026-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
