# Generated by Django 5.2.17 on 2026-09-28 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_flashcard_created_at_alter_flashcard_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
